name: Grill My Code

on:
  push:
  workflow_dispatch:

jobs:
  question-generator:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write # required to create the GitHub Issue
      models: read # required to call GitHub Models API
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # full history required for diff resolution

      - uses: NSCC-ITC-Assessment/GrillMyCode@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ai_model: "gpt-4.1"
          post_issue: "true"
          num_questions: "50"
          include_patterns: "**/*.cpp,**/*.h"
          additional_context: "The questions should be targeted at a second-year college student taking a course in data structures and algorithms. The questions should focus on verifying a student's understanding and comprehension of the generated code. If the question targets code in a function that has fewer than 5 lines of code, include the entire function in the question for context. If the question targets code in a function that has 5 or more lines of code, include the entire function in the question for context."
