name: Grill My Code

on:
  push:
  workflow_dispatch:

jobs:
  question-generator:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write # required to create the GitHub Issue
      models: read # required to call GitHub Models API
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # full history required for diff resolution

      - uses: NSCC-ITC-Assessment/GrillMyCode@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ai_model: "gpt-4.1"
          post_issue: "true"
          num_questions: "50"